# Generated by Django 2.2 on 2019-04-17 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 18, 16, 19, 58, 549486, tzinfo=utc))),
            ],
        ),
    ]
